-- Premier Planner - consolidated fresh-install schema
-- Target: a new Supabase project
-- Run as a single query in Supabase SQL Editor.

begin;

create extension if not exists pgcrypto;

-- ---------- shared helpers ----------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------- authentication profiles ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'player' check (role in ('player', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id, email)
  values (new.id, new.email)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles(id, email)
select id, email from auth.users
on conflict (id) do update set email = excluded.email;

create or replace function public.is_current_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- ---------- core team data ----------
create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(trim(name)) between 1 and 100),
  user_id uuid unique references public.profiles(id) on delete set null,
  discord_id text unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agents (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(trim(name)) between 1 and 100),
  role text not null default 'Duelista',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.maps (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(trim(name)) between 1 and 100),
  in_pool boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_agents (
  player_id bigint not null references public.players(id) on delete cascade,
  agent_id bigint not null references public.agents(id) on delete cascade,
  level text check (level in ('great', 'good', 'normal', 'bad', 'none')),
  updated_at timestamptz not null default now(),
  primary key (player_id, agent_id)
);

-- ---------- compositions ----------
create table if not exists public.compositions (
  id bigint generated by default as identity primary key,
  map_id bigint not null references public.maps(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 100),
  notes text,
  is_main boolean not null default false,
  status text not null default 'active'
    check (status in ('active', 'draft', 'discarded')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (map_id, name)
);

create unique index if not exists compositions_one_main_per_map
on public.compositions(map_id)
where is_main = true;

create table if not exists public.composition_slots (
  composition_id bigint not null references public.compositions(id) on delete cascade,
  slot smallint not null check (slot between 1 and 5),
  player_id bigint references public.players(id) on delete set null,
  agent_id bigint references public.agents(id) on delete set null,
  primary key (composition_id, slot)
);

create or replace function public.normalize_composition_status()
returns trigger
language plpgsql
as $$
begin
  if new.status <> 'active' then
    new.is_main := false;
  end if;
  return new;
end;
$$;

drop trigger if exists compositions_normalize_status on public.compositions;
create trigger compositions_normalize_status
before insert or update of status, is_main on public.compositions
for each row execute function public.normalize_composition_status();

create or replace function public.save_composition(
  p_id bigint,
  p_map_id bigint,
  p_name text,
  p_notes text,
  p_is_main boolean,
  p_slots jsonb
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  v_slot jsonb;
begin
  if not public.is_current_admin() then
    raise exception 'Solo un administrador puede guardar composiciones';
  end if;

  if p_is_main then
    update public.compositions
    set is_main = false
    where map_id = p_map_id and (p_id is null or id <> p_id);
  end if;

  if p_id is null then
    insert into public.compositions(map_id, name, notes, is_main)
    values (p_map_id, trim(p_name), p_notes, p_is_main)
    returning id into v_id;
  else
    update public.compositions
    set map_id = p_map_id,
        name = trim(p_name),
        notes = p_notes,
        is_main = p_is_main,
        updated_at = now()
    where id = p_id
    returning id into v_id;
    if v_id is null then raise exception 'La composición no existe'; end if;
  end if;

  delete from public.composition_slots where composition_id = v_id;
  for v_slot in select * from jsonb_array_elements(coalesce(p_slots, '[]'::jsonb))
  loop
    insert into public.composition_slots(composition_id, slot, player_id, agent_id)
    values (
      v_id,
      (v_slot->>'slot')::smallint,
      nullif(v_slot->>'player_id', '')::bigint,
      nullif(v_slot->>'agent_id', '')::bigint
    );
  end loop;
  return v_id;
end;
$$;

-- ---------- calendar ----------
create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('season', 'match_days', 'play_day')),
  title text not null check (char_length(trim(title)) between 1 and 150),
  map_id bigint references public.maps(id) on delete set null,
  start_date date not null,
  end_date date,
  event_time time,
  notes text,
  occurrences jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or end_date >= start_date)
);

-- ---------- attendance ----------
create table if not exists public.attendance_polls (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) between 1 and 100),
  map_id bigint references public.maps(id) on delete set null,
  source_event_id bigint references public.calendar_events(id) on delete set null,
  status text not null default 'open' check (status in ('open', 'closed')),
  selected_option_id bigint,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  closed_at timestamptz,
  opened_notified_at timestamptz,
  closed_notified_at timestamptz
);

create table if not exists public.attendance_options (
  id bigint generated by default as identity primary key,
  poll_id bigint not null references public.attendance_polls(id) on delete cascade,
  event_date date not null,
  event_time time,
  sort_order integer not null default 0,
  unique (poll_id, event_date, event_time)
);

alter table public.attendance_polls
  drop constraint if exists attendance_polls_selected_option_id_fkey;
alter table public.attendance_polls
  add constraint attendance_polls_selected_option_id_fkey
  foreign key (selected_option_id)
  references public.attendance_options(id)
  on delete set null;

create table if not exists public.attendance_votes (
  poll_id bigint not null references public.attendance_polls(id) on delete cascade,
  option_id bigint not null references public.attendance_options(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  choice text not null check (choice in ('available', 'maybe', 'unavailable')),
  updated_at timestamptz not null default now(),
  primary key (option_id, player_id)
);

create or replace function public.open_attendance_poll(
  p_title text,
  p_map_id bigint,
  p_source_event_id bigint,
  p_options jsonb
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_poll_id bigint;
  v_item jsonb;
begin
  if not public.is_current_admin() then
    raise exception 'Solo un administrador puede abrir votaciones';
  end if;
  if jsonb_array_length(coalesce(p_options, '[]'::jsonb)) = 0 then
    raise exception 'La votación necesita al menos una fecha';
  end if;

  insert into public.attendance_polls(title, map_id, source_event_id, created_by)
  values (trim(p_title), p_map_id, p_source_event_id, auth.uid())
  returning id into v_poll_id;

  for v_item in select * from jsonb_array_elements(p_options)
  loop
    insert into public.attendance_options(poll_id, event_date, event_time, sort_order)
    values (
      v_poll_id,
      (v_item->>'date')::date,
      nullif(v_item->>'time', '')::time,
      coalesce((v_item->>'sort_order')::integer, 0)
    );
  end loop;
  return v_poll_id;
end;
$$;

create or replace function public.vote_attendance(
  p_option_id bigint,
  p_choice text
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_poll_id bigint;
  v_player_id bigint;
begin
  if p_choice not in ('available', 'maybe', 'unavailable') then
    raise exception 'Opción de voto no válida';
  end if;

  select o.poll_id into v_poll_id
  from public.attendance_options o
  join public.attendance_polls p on p.id = o.poll_id
  where o.id = p_option_id and p.status = 'open';
  if v_poll_id is null then raise exception 'La votación está cerrada'; end if;

  select id into v_player_id
  from public.players
  where user_id = auth.uid();
  if v_player_id is null then
    raise exception 'Tu cuenta no está vinculada a un jugador';
  end if;

  insert into public.attendance_votes(poll_id, option_id, player_id, choice, updated_at)
  values (v_poll_id, p_option_id, v_player_id, p_choice, now())
  on conflict (option_id, player_id)
  do update set choice = excluded.choice, updated_at = now();
end;
$$;

create or replace function public.close_attendance_poll(
  p_poll_id bigint,
  p_selected_option_id bigint
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_poll public.attendance_polls%rowtype;
  v_option public.attendance_options%rowtype;
  v_event_id bigint;
begin
  if not public.is_current_admin() then
    raise exception 'Solo un administrador puede cerrar votaciones';
  end if;

  select * into v_poll
  from public.attendance_polls
  where id = p_poll_id and status = 'open'
  for update;
  if v_poll.id is null then raise exception 'La votación no está abierta'; end if;

  select * into v_option
  from public.attendance_options
  where id = p_selected_option_id and poll_id = p_poll_id;
  if v_option.id is null then
    raise exception 'La fecha elegida no pertenece a la votación';
  end if;

  insert into public.calendar_events(
    type, title, map_id, start_date, event_time, notes, occurrences
  ) values (
    'play_day', v_poll.title, v_poll.map_id, v_option.event_date,
    v_option.event_time, 'Fecha seleccionada mediante votación de asistencia',
    '[]'::jsonb
  ) returning id into v_event_id;

  update public.attendance_polls
  set status = 'closed',
      selected_option_id = v_option.id,
      closed_at = now()
  where id = p_poll_id;
  return v_event_id;
end;
$$;

-- ---------- matches and statistics ----------
create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  match_type text not null check (match_type in ('premier', 'ranked')),
  calendar_event_id bigint references public.calendar_events(id) on delete set null,
  played_at date not null,
  result text not null,
  team_score smallint not null check (team_score between 0 and 99),
  opponent_score smallint not null check (opponent_score between 0 and 99),
  map_id bigint not null references public.maps(id) on delete restrict,
  composition_id bigint references public.compositions(id) on delete set null,
  notes text,
  result_image_url text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matches_result_check check (
    result in ('win', 'loss')
    or (match_type = 'ranked' and result = 'draw')
  ),
  constraint matches_premier_event check (
    (match_type = 'premier' and calendar_event_id is not null)
    or (match_type = 'ranked' and calendar_event_id is null)
  )
);

create table if not exists public.match_player_stats (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  agent_id bigint not null references public.agents(id) on delete restrict,
  acs smallint not null default 0 check (acs >= 0),
  kills smallint not null default 0 check (kills >= 0),
  deaths smallint not null default 0 check (deaths >= 0),
  assists smallint not null default 0 check (assists >= 0),
  first_bloods smallint not null default 0 check (first_bloods >= 0),
  trades smallint not null default 0 check (trades >= 0),
  plants smallint not null default 0 check (plants >= 0),
  defuses smallint not null default 0 check (defuses >= 0),
  unique (match_id, player_id)
);

-- ---------- Discord integration ----------
create table if not exists public.discord_bot_settings (
  guild_id bigint primary key,
  main_channel_id bigint not null,
  configured_by bigint,
  updated_at timestamptz not null default now()
);

create table if not exists public.discord_notifications_sent (
  event_id bigint not null references public.calendar_events(id) on delete cascade,
  notification_type text not null check (
    notification_type in ('three_days', 'same_day', 'one_hour', 'fifteen_minutes')
  ),
  sent_at timestamptz not null default now(),
  primary key (event_id, notification_type)
);

-- ---------- indexes ----------
create index if not exists players_sort_idx on public.players(sort_order, name);
create index if not exists compositions_map_idx on public.compositions(map_id, status);
create index if not exists composition_slots_comp_idx on public.composition_slots(composition_id);
create index if not exists calendar_events_date_idx on public.calendar_events(start_date);
create index if not exists attendance_options_poll_idx on public.attendance_options(poll_id);
create index if not exists attendance_votes_poll_idx on public.attendance_votes(poll_id);
create index if not exists matches_played_at_idx on public.matches(played_at desc);
create index if not exists matches_event_idx on public.matches(calendar_event_id);
create index if not exists match_player_stats_match_idx on public.match_player_stats(match_id);
create index if not exists match_player_stats_player_idx on public.match_player_stats(player_id);

-- ---------- updated_at triggers ----------
do $$
declare
  t text;
begin
  foreach t in array array[
    'profiles', 'players', 'agents', 'maps', 'compositions',
    'calendar_events', 'matches'
  ]
  loop
    execute format('drop trigger if exists %I_set_updated_at on public.%I', t, t);
    execute format(
      'create trigger %I_set_updated_at before update on public.%I '
      'for each row execute function public.set_updated_at()', t, t
    );
  end loop;
end $$;

-- ---------- Row Level Security ----------
alter table public.profiles enable row level security;
alter table public.players enable row level security;
alter table public.agents enable row level security;
alter table public.maps enable row level security;
alter table public.player_agents enable row level security;
alter table public.compositions enable row level security;
alter table public.composition_slots enable row level security;
alter table public.calendar_events enable row level security;
alter table public.attendance_polls enable row level security;
alter table public.attendance_options enable row level security;
alter table public.attendance_votes enable row level security;
alter table public.matches enable row level security;
alter table public.match_player_stats enable row level security;
alter table public.discord_bot_settings enable row level security;
alter table public.discord_notifications_sent enable row level security;

-- Public Planner data can be read by the static site.
do $$
declare
  t text;
begin
  foreach t in array array[
    'players', 'agents', 'maps', 'player_agents', 'compositions',
    'composition_slots', 'calendar_events'
  ]
  loop
    execute format('drop policy if exists public_read on public.%I', t);
    execute format('create policy public_read on public.%I for select using (true)', t);
    execute format('drop policy if exists admin_manage on public.%I', t);
    execute format(
      'create policy admin_manage on public.%I for all to authenticated '
      'using (public.is_current_admin()) with check (public.is_current_admin())', t
    );
  end loop;
end $$;

-- Authenticated users can read attendance and statistics; admins manage them.
do $$
declare
  t text;
begin
  foreach t in array array[
    'attendance_polls', 'attendance_options', 'attendance_votes',
    'matches', 'match_player_stats'
  ]
  loop
    execute format('drop policy if exists authenticated_read on public.%I', t);
    execute format(
      'create policy authenticated_read on public.%I for select '
      'to authenticated using (true)', t
    );
    execute format('drop policy if exists admin_manage on public.%I', t);
    execute format(
      'create policy admin_manage on public.%I for all to authenticated '
      'using (public.is_current_admin()) with check (public.is_current_admin())', t
    );
  end loop;
end $$;

-- A player may insert/update their own attendance votes directly as a fallback.
drop policy if exists own_vote_insert on public.attendance_votes;
create policy own_vote_insert on public.attendance_votes
for insert to authenticated
with check (
  exists (
    select 1 from public.players p
    where p.id = player_id and p.user_id = auth.uid()
  )
);
drop policy if exists own_vote_update on public.attendance_votes;
create policy own_vote_update on public.attendance_votes
for update to authenticated
using (
  exists (
    select 1 from public.players p
    where p.id = player_id and p.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.players p
    where p.id = player_id and p.user_id = auth.uid()
  )
);

-- Profiles: users see themselves; admins see and manage all.
drop policy if exists profile_read on public.profiles;
create policy profile_read on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_current_admin());
drop policy if exists profile_admin_manage on public.profiles;
create policy profile_admin_manage on public.profiles
for all to authenticated
using (public.is_current_admin())
with check (public.is_current_admin());

-- Discord tables are intentionally service-role only. RLS has no client policy.

-- ---------- grants ----------
grant usage on schema public to anon, authenticated;
grant select on public.players, public.agents, public.maps,
  public.player_agents, public.compositions, public.composition_slots,
  public.calendar_events to anon, authenticated;
grant select on public.profiles, public.attendance_polls,
  public.attendance_options, public.attendance_votes,
  public.matches, public.match_player_stats to authenticated;
grant insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.save_composition(bigint,bigint,text,text,boolean,jsonb) to authenticated;
grant execute on function public.open_attendance_poll(text,bigint,bigint,jsonb) to authenticated;
grant execute on function public.vote_attendance(bigint,text) to authenticated;
grant execute on function public.close_attendance_poll(bigint,bigint) to authenticated;

-- ---------- Storage ----------
insert into storage.buckets(id, name, public)
values ('match-results', 'match-results', true)
on conflict (id) do update set public = true;

drop policy if exists public_read_match_results on storage.objects;
create policy public_read_match_results
on storage.objects for select
using (bucket_id = 'match-results');

drop policy if exists admin_insert_match_results on storage.objects;
create policy admin_insert_match_results
on storage.objects for insert to authenticated
with check (bucket_id = 'match-results' and public.is_current_admin());

drop policy if exists admin_update_match_results on storage.objects;
create policy admin_update_match_results
on storage.objects for update to authenticated
using (bucket_id = 'match-results' and public.is_current_admin())
with check (bucket_id = 'match-results' and public.is_current_admin());

drop policy if exists admin_delete_match_results on storage.objects;
create policy admin_delete_match_results
on storage.objects for delete to authenticated
using (bucket_id = 'match-results' and public.is_current_admin());

-- ---------- Realtime for attendance ----------
do $$
begin
  alter publication supabase_realtime add table public.attendance_polls;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.attendance_options;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.attendance_votes;
exception when duplicate_object then null;
end $$;

commit;

-- After running this file:
-- 1. Create a user in Authentication -> Users.
-- 2. Promote the first administrator:
--    update public.profiles set role = 'admin' where email = 'admin@example.com';
